/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["f-form-builder should render object field with all default properties"] = 
`<f-div
  align="top-left"
  direction="column"
  gap="small"
  height="fill-container"
  overflow="wrap"
  padding="none"
  selected="none"
  state="transparent"
  sticky="none"
  style="padding: 0px; width: 100%;"
  variant="block"
  width="100%"
>
  <f-form-group
    collapse="none"
    direction="horizontal"
    gap="medium"
    label="{&quot;title&quot;:&quot;Object field form&quot;,&quot;description&quot;:&quot;showing object field&quot;}"
  >
    <f-input
      category="fill"
      clear=""
      name="firstname"
      size="medium"
      state="default"
      type="text"
      value="Tony"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        firstname
      </f-div>
    </f-input>
    <f-input
      category="fill"
      clear=""
      name="lastname"
      size="medium"
      state="default"
      type="text"
      value="Stark"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        lastname
      </f-div>
    </f-input>
  </f-form-group>
</f-div>
`;
/* end snapshot f-form-builder should render object field with all default properties */

snapshots["f-form-builder should emit state-change with validation messages"] = 
`<f-div
  align="top-left"
  direction="column"
  gap="small"
  height="fill-container"
  overflow="wrap"
  padding="none"
  selected="none"
  state="transparent"
  sticky="none"
  style="padding: 0px; width: 100%;"
  variant="block"
  width="100%"
>
  <f-form-group
    collapse="none"
    direction="horizontal"
    gap="medium"
    label="{&quot;title&quot;:&quot;Object field form&quot;,&quot;description&quot;:&quot;showing object field&quot;}"
  >
    <f-input
      category="fill"
      clear=""
      name="firstname"
      size="medium"
      state="default"
      type="text"
      value="Tony"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        firstname
      </f-div>
    </f-input>
    <f-input
      category="fill"
      clear=""
      name="lastname"
      size="medium"
      state="default"
      type="text"
      value="Stark"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        lastname
      </f-div>
    </f-input>
  </f-form-group>
</f-div>
`;
/* end snapshot f-form-builder should emit state-change with validation messages */

snapshots["f-form-builder should display array fields"] = 
`<f-div
  align="top-left"
  direction="column"
  gap="small"
  height="fill-container"
  overflow="wrap"
  padding="none"
  selected="none"
  state="transparent"
  sticky="none"
  style="padding: 0px; width: 100%;"
  variant="block"
  width="100%"
>
  <f-div
    align="top-left"
    direction="column"
    gap="medium"
    height="fill-container"
    overflow="wrap"
    padding="none"
    selected="none"
    state="transparent"
    sticky="none"
    style="padding: 0px;"
    variant="block"
    width="fill-container"
  >
    <f-div
      align="top-left"
      direction="row"
      gap="small"
      height="fill-container"
      overflow="scroll"
      padding="none"
      selected="none"
      state="transparent"
      sticky="none"
      style="padding: 0px;"
      variant="block"
      width="fill-container"
    >
      <f-input
        category="fill"
        clear=""
        name=""
        size="medium"
        state="default"
        type="text"
        value="username1"
        variant="curved"
      >
        <f-div
          align="top-left"
          direction="row"
          gap="none"
          height="fill-container"
          overflow="wrap"
          padding="none"
          selected="none"
          slot="label"
          state="transparent"
          sticky="none"
          style="padding: 0px;"
          variant="block"
          width="fill-container"
        >
        </f-div>
      </f-input>
      <f-icon-button
        icon="i-plus"
        size="x-small"
        state="neutral"
      >
      </f-icon-button>
    </f-div>
    <f-div
      align="top-left"
      direction="row"
      gap="small"
      height="fill-container"
      overflow="scroll"
      padding="none"
      selected="none"
      state="transparent"
      sticky="none"
      style="padding: 0px;"
      variant="block"
      width="fill-container"
    >
      <f-input
        category="fill"
        clear=""
        name=""
        size="medium"
        state="default"
        type="text"
        value="username2"
        variant="curved"
      >
        <f-div
          align="top-left"
          direction="row"
          gap="none"
          height="fill-container"
          overflow="wrap"
          padding="none"
          selected="none"
          slot="label"
          state="transparent"
          sticky="none"
          style="padding: 0px;"
          variant="block"
          width="fill-container"
        >
        </f-div>
      </f-input>
      <f-icon-button
        icon="i-minus"
        size="x-small"
        state="danger"
      >
      </f-icon-button>
    </f-div>
  </f-div>
  <slot name="help">
  </slot>
</f-div>
`;
/* end snapshot f-form-builder should display array fields */

snapshots["f-form-builder should add/delete field in array"] = 
`<f-div
  align="top-left"
  direction="column"
  gap="small"
  height="fill-container"
  overflow="wrap"
  padding="none"
  selected="none"
  state="transparent"
  sticky="none"
  style="padding: 0px; width: 100%;"
  variant="block"
  width="100%"
>
  <f-div
    align="top-left"
    direction="column"
    gap="medium"
    height="fill-container"
    overflow="wrap"
    padding="none"
    selected="none"
    state="transparent"
    sticky="none"
    style="padding: 0px;"
    variant="block"
    width="fill-container"
  >
    <f-div
      align="top-left"
      direction="row"
      gap="small"
      height="fill-container"
      overflow="scroll"
      padding="none"
      selected="none"
      state="transparent"
      sticky="none"
      style="padding: 0px;"
      variant="block"
      width="fill-container"
    >
      <f-input
        category="fill"
        clear=""
        name=""
        size="medium"
        state="default"
        type="text"
        value="username1"
        variant="curved"
      >
        <f-div
          align="top-left"
          direction="row"
          gap="none"
          height="fill-container"
          overflow="wrap"
          padding="none"
          selected="none"
          slot="label"
          state="transparent"
          sticky="none"
          style="padding: 0px;"
          variant="block"
          width="fill-container"
        >
        </f-div>
      </f-input>
      <f-icon-button
        icon="i-plus"
        size="x-small"
        state="neutral"
      >
      </f-icon-button>
    </f-div>
    <f-div
      align="top-left"
      direction="row"
      gap="small"
      height="fill-container"
      overflow="scroll"
      padding="none"
      selected="none"
      state="transparent"
      sticky="none"
      style="padding: 0px;"
      variant="block"
      width="fill-container"
    >
      <f-input
        category="fill"
        clear=""
        name=""
        size="medium"
        state="default"
        type="text"
        value="username2"
        variant="curved"
      >
        <f-div
          align="top-left"
          direction="row"
          gap="none"
          height="fill-container"
          overflow="wrap"
          padding="none"
          selected="none"
          slot="label"
          state="transparent"
          sticky="none"
          style="padding: 0px;"
          variant="block"
          width="fill-container"
        >
        </f-div>
      </f-input>
      <f-icon-button
        icon="i-minus"
        size="x-small"
        state="danger"
      >
      </f-icon-button>
    </f-div>
  </f-div>
  <slot name="help">
  </slot>
</f-div>
`;
/* end snapshot f-form-builder should add/delete field in array */

snapshots["f-form-builder should test snapshot of all fields"] = 
`<f-div
  align="top-left"
  direction="column"
  gap="small"
  height="fill-container"
  overflow="wrap"
  padding="none"
  selected="none"
  state="transparent"
  sticky="none"
  style="padding: 0px; width: 100%;"
  variant="block"
  width="100%"
>
  <f-form-group
    collapse="none"
    direction="vertical"
    gap="medium"
    label="{&quot;title&quot;:&quot;Object level label&quot;,&quot;description&quot;:&quot;following fields are used for demo purpose only&quot;}"
  >
    <f-select
      category="fill"
      clear=""
      height="180"
      icon-left="i-app"
      name="selectBox"
      options="[&quot;option 1&quot;,&quot;option 2&quot;,&quot;option 3&quot;]"
      placeholder="This is a placeholder"
      selection-limit="2"
      size="medium"
      state="default"
      type="multiple"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        Select multiple option to test
      </f-div>
    </f-select>
    <f-divider
      id="selectBox-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-input
      category="fill"
      clear=""
      name="textField"
      size="medium"
      state="default"
      suffix="recommended"
      type="text"
      value="vikas"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        textField
      </f-div>
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="help"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        This field is a required field
      </f-div>
    </f-input>
    <f-divider
      id="textField-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-input
      category="fill"
      clear=""
      data-hidden="false"
      name="eventTestField"
      size="medium"
      state="default"
      type="text"
      variant="curved"
    >
      (event) => {
              console.log("onMouseOver callback triggered", event);
            }
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        eventTestField
      </f-div>
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="help"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        This field is a required field
      </f-div>
    </f-input>
    <f-divider
      data-hidden="false"
      id="eventTestField-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-switch
      category="fill"
      name="switchButton"
      size="medium"
      state="default"
      value="false"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        switchButton
      </f-div>
    </f-switch>
    <f-divider
      id="switchButton-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-radio-group
      category="fill"
      direction="vertical"
      gap="small"
      name="radio"
      options="[{&quot;id&quot;:&quot;or&quot;,&quot;title&quot;:&quot;Orange&quot;,&quot;iconTooltip&quot;:&quot;hello&quot;},{&quot;id&quot;:&quot;banannaId&quot;,&quot;iconTooltip&quot;:&quot;hello&quot;,&quot;description&quot;:&quot;Check if you like Banana&quot;}]"
      size="medium"
      state="default"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        Radios
      </f-div>
    </f-radio-group>
    <f-divider
      id="radio-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-checkbox-group
      category="fill"
      direction="horizontal"
      gap="small"
      name="checkboxField"
      options="[{&quot;id&quot;:&quot;or&quot;,&quot;title&quot;:&quot;Orange&quot;,&quot;iconTooltip&quot;:&quot;hello&quot;,&quot;description&quot;:&quot;Orange has Vitamin C&quot;},{&quot;id&quot;:&quot;banannaId&quot;,&quot;iconTooltip&quot;:&quot;hello&quot;,&quot;description&quot;:&quot;Banana is cheap but rich in fiber&quot;}]"
      size="medium"
      state="default"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        Check/Uncheck options
      </f-div>
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="description"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        this my checkbox
      </f-div>
    </f-checkbox-group>
    <f-divider
      id="checkboxField-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-text-area
      category="fill"
      clear=""
      max-length="100"
      name="textAreaField"
      placeholder="This is a placeholder"
      size="medium"
      state="default"
      variant="curved"
    >
      <f-div
        align="top-left"
        direction="row"
        gap="none"
        height="fill-container"
        overflow="wrap"
        padding="none"
        selected="none"
        slot="label"
        state="transparent"
        sticky="none"
        style="padding: 0px;"
        variant="block"
        width="fill-container"
      >
        textAreaField
      </f-div>
    </f-text-area>
    <f-divider
      id="textAreaField-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-form-object
      category="fill"
      gap="medium"
      name="nestedObject"
      size="medium"
      state="default"
      variant="curved"
    >
    </f-form-object>
    <f-divider
      id="nestedObject-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-form-array
      category="fill"
      gap="medium"
      name="nestedArray"
      size="medium"
      state="default"
      variant="curved"
    >
    </f-form-array>
    <f-divider
      id="nestedArray-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
    <f-button
      category="fill"
      icon-left="i-arrow-rotate"
      name="getButton"
      size="medium"
      state="primary"
      variant="curved"
    >
    </f-button>
    <f-divider
      id="getButton-divider"
      size="medium"
      state="default"
      variant="solid"
    >
    </f-divider>
  </f-form-group>
</f-div>
`;
/* end snapshot f-form-builder should test snapshot of all fields */

